# Generated by Django 4.2.7 on 2024-01-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('receiver_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('ammount', models.IntegerField()),
                ('service_description', models.TextField()),
                ('payment_done', models.BooleanField(default=False)),
                ('service_done', models.BooleanField(default=False)),
            ],
        ),
    ]
