# Generated by Django 4.2.7 on 2024-01-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='transaction_id',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
